<h1 style="
    background-color: #251351; 
    color: white; 
    padding: 10px; 
    text-align: left; 
    font-family: Arial, sans-serif; 
    font-size: 32px; 
    font-weight: bold; 
    margin: 10px 0;">
    05 - Trabalhando com banco de dados
</h1>  

O time de dados de uma Instituição Financeira possui um arquivo CSV que contém os dados de todos os clientes cadastrados. Porém, o que eles querem é pegar esse arquivo, colocar em um banco de dados local e a partir dele realizar consultas SQL. Assim será possível analisar dados, obter insights e tomar decisões estratégicas.



[Documentação SQLAlchemy](https://www.sqlalchemy.org/)  

**Python e Bancos de Dados - Resumo**  
Python possui diversas bibliotecas para bancos de dados, como SQLite, MySQL, PostgreSQL e MongoDB. O pacote `sqlite3` é amplamente utilizado para trabalhar com SQLite, um banco de dados leve que não exige servidor e já vem instalado no Google Colab.

Para facilitar a interação com bancos relacionais, a biblioteca **SQLAlchemy** fornece um **ORM (Object-Relational Mapping)**, permitindo manipular bancos de dados usando código Python, sem precisar escrever diretamente em SQL. Isso torna o código mais legível, fácil de manter e menos propenso a erros.

Além disso, SQLAlchemy suporta consultas complexas e grandes volumes de dados, sendo ideal para aplicações que lidam com grandes conjuntos de informações.





In [22]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

# text -> interpreta Cláusulas SQL puras

In [23]:
# memory indica que estamos usando um banco de dados local
engine = create_engine('sqlite:///:memory:')

In [24]:
import pandas as pd

In [25]:
df_banco = pd.read_csv('data/clientes_banco.csv')
df_banco.head(5)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

In [26]:
# Criando a base de dados SQL: DataFrame em formato de banco
df_banco.to_sql(name='clientes', con=engine, index=False)

438463

In [27]:
# Inspecionar o banco de dados
inspector = inspect(subject=engine)

In [28]:
# Nome das tabelas no banco de dados
inspector.get_table_names()

['clientes']

<h2 style="
    background-color: #251351; 
    color: white; 
    padding: 10px; 
    text-align: left; 
    font-family: Arial, sans-serif; 
    font-size: 32px; 
    font-weight: bold; 
    margin: 10px 0;">
    Cláusulas SQL
</h2>  

As instruções SQL podem ser compostas por uma ou mais cláusulas que fornecem informações adicionais sobre o que a consulta deve fazer. As cláusulas mais comuns são:

`SELECT`: especifica quais colunas devem ser selecionadas na consulta.  
`FROM`: especifica as tabelas do banco de dados que devem ser consultadas.  
`WHERE`: filtra os resultados da consulta com base em uma ou mais condições especificadas.  
`ORDER BY`: classifica os resultados da consulta em ordem crescente ou decrescente com base em uma ou mais colunas.  
`GROUP BY`: agrupa os resultados da consulta com base em uma ou mais colunas.  
`LIMIT`: limita o número de linhas retornadas pelos resultados da consulta.  

__Exemplo__:
```sql
SELECT nome, sobrenome, salario
FROM colaboradores
WHERE departamento = 'vendas'
```
 


In [29]:
df_banco.head(2)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   

  Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0          Empregado    Outro              12          427500.0          1   
1          Empregado    Outro              12          427500.0          1   

               Moradia  
0  Apartamento alugado  
1  Apartamento alugado

In [30]:
# Consulta por DataFrame
df_banco.query("Categoria_de_renda == 'Empregado' ")

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
10         5008815     46   Ensino superior         Casado                2   
11         5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
438448     6837905     43      Ensino médio         Casado                3   
438449     6837906     43      Ensino médio         Casado                3   
438454     6839936     34      Ensino médio         Casado                3   
438459     6840222     43      Ensino médio       Solteiro                1   
438462     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
10              Empregado     Contabilidade               2          270000.0   
11              Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
438448          Empregado             Outro               7          355050.0   
438449          Empregado             Outro               7          355050.0   
438454          Empregado  Construção Civil               5          135000.0   
438459          Empregado  Construção Civil               8          103500.0   
438462          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
10              1  Casa/apartamento próprio  
11              1  Casa/apartamento próprio  
...           ...                       ...  
438448          1  Casa/apartamento próprio  
438449          1  Casa/apartamento próprio  
438454          1  Casa/apartamento próprio  
438459          0  Casa/apartamento próprio  
438462          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

In [31]:
# Seperar categoria de renda 'empregado'
query_empregados = "SELECT * FROM clientes WHERE Categoria_de_renda='Empregado'"

# Read SQL query or database table into a DataFrame.
pd.read_sql(query_empregados, engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

In [32]:
df_empregados = pd.read_sql(query_empregados, engine)

df_empregados.to_sql('empregados_banco', con=engine, index=False)

226059

In [33]:
# Ler uma tabela SQL
pd.read_sql_table('empregados_banco', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

__Quando usar `pd.read_sql`, `pd.read_sql_table` e `pd.read_sql_query`?__  
 
| Função | Aceita Query SQL? | Aceita Nome de Tabela? | Quando usar? |
|--------|----------------|-----------------|-------------|
| `pd.read_sql` | ✅ Sim | ✅ Sim | Para flexibilidade entre query e tabela |
| `pd.read_sql_query` | ✅ Sim | ❌ Não | Para consultas SQL mais complexas |
| `pd.read_sql_table` | ❌ Não | ✅ Sim | Para carregar uma tabela completa |


In [34]:
pd.read_sql_table('empregados_banco', engine, columns=['ID_Cliente', 'Grau_escolaridade'])

ID_Cliente Grau_escolaridade
0          5008804   Ensino superior
1          5008805   Ensino superior
2          5008806      Ensino médio
3          5008815   Ensino superior
4          5112956   Ensino superior
...            ...               ...
226054     6837905      Ensino médio
226055     6837906      Ensino médio
226056     6839936      Ensino médio
226057     6840222      Ensino médio
226058     6842885      Ensino médio

[226059 rows x 2 columns]

In [35]:
pd.read_sql('SELECT * FROM clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [36]:
delete_first_user_query = "DELETE FROM clientes WHERE ID_Cliente=5008804"
# Cláusula pura
delete_first_user_query = text(delete_first_user_query)

with engine.connect() as conn:
    conn.execute(delete_first_user_query)
    conn.commit()

In [37]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52      Ensino médio       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

O cliente de ID 5008804 foi deletado da base de dados!

In [38]:
# Atualizar o db
with engine.connect() as conn:
    conn.execute(text('UPDATE clientes SET Grau_escolaridade="Ensino Superior" WHERE ID_Cliente=5008808'))
    conn.commit()


In [39]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino Superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

__Desafio__  
1. Criar o banco de dados local com a biblioteca SQLAlchemy. ✅  
2. Escrever os dados do arquivo CSV neste banco de dados local. ✅ 
3. Realizar três atualizações no banco de dados:  
- Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.  
Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.  
- Criar um novo registro de cliente seguindo as especificações abaixo:  
    ID_Cliente: 6850985  
    Idade: 33  
    Grau_escolaridade: Doutorado  
    Estado_civil: Solteiro  
    Tamanho_familia: 1  
    Categoria_de_renda: Empregado  
    Ocupacao: TI  
    Anos_empregado: 2  
    Rendimento_anual: 290000  
    Tem_carro: 0  
    Moradia: Casa/apartamento próprio  



In [40]:
pd.read_sql_table('clientes', engine).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438462 entries, 0 to 438461
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   ID_Cliente          438462 non-null  int64  
 1   Idade               438462 non-null  int64  
 2   Grau_escolaridade   438462 non-null  object 
 3   Estado_civil        438462 non-null  object 
 4   Tamanho_familia     438462 non-null  int64  
 5   Categoria_de_renda  438462 non-null  object 
 6   Ocupacao            438462 non-null  object 
 7   Anos_empregado      438462 non-null  int64  
 8   Rendimento_anual    438462 non-null  float64
 9   Tem_carro           438462 non-null  int64  
 10  Moradia             438462 non-null  object 
dtypes: float64(1), int64(5), object(5)
memory usage: 36.8+ MB


In [42]:
df_clientes_temp = pd.read_sql_table('clientes', engine)
df_clientes_temp

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino Superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

In [45]:
# Verificando antes da alteração
df_clientes_temp.query('ID_Cliente==6840104')

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
438457     6840104     62      Ensino médio   Divorciado                1   

       Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  \
438457        Pensionista    Outro               0          135000.0   

        Tem_carro                   Moradia  
438457          0  Casa/apartamento próprio

In [46]:
query_id_6840104 = "UPDATE clientes SET Rendimento_anual=300000 WHERE ID_Cliente=6840104"

# Atualização na base de dados
with engine.connect() as conn:
    conn.execute(text(query_id_6840104))
    conn.commit()

In [47]:
pd.read_sql_table('clientes', engine).query('ID_Cliente==6840104')

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
438457     6840104     62      Ensino médio   Divorciado                1   

       Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  \
438457        Pensionista    Outro               0          300000.0   

        Tem_carro                   Moradia  
438457          0  Casa/apartamento próprio

In [48]:
# Excluir o registro do cliente 5008809
df_clientes_temp.query('ID_Cliente==5008809') ## index=3

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
3     5008809     52      Ensino médio     Solteiro                1   

    Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
3  Associado comercial   Vendas               8          270000.0          0   

                    Moradia  
3  Casa/apartamento próprio

In [49]:
query_id_5008809 = "DELETE FROM clientes WHERE ID_Cliente=5008809"

# Atualização na base de dados
with engine.connect() as conn:
    conn.execute(text(query_id_5008809))
    conn.commit()

In [53]:
pd.read_sql_table('clientes', con=engine).query('ID_Cliente==5008809') ## index=3

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

In [59]:
df_clientes_temp.columns

Index(['ID_Cliente', 'Idade', 'Grau_escolaridade', 'Estado_civil',
       'Tamanho_familia', 'Categoria_de_renda', 'Ocupacao', 'Anos_empregado',
       'Rendimento_anual', 'Tem_carro', 'Moradia'],
      dtype='object')

In [61]:
df_clientes_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438462 entries, 0 to 438461
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   ID_Cliente          438462 non-null  int64  
 1   Idade               438462 non-null  int64  
 2   Grau_escolaridade   438462 non-null  object 
 3   Estado_civil        438462 non-null  object 
 4   Tamanho_familia     438462 non-null  int64  
 5   Categoria_de_renda  438462 non-null  object 
 6   Ocupacao            438462 non-null  object 
 7   Anos_empregado      438462 non-null  int64  
 8   Rendimento_anual    438462 non-null  float64
 9   Tem_carro           438462 non-null  int64  
 10  Moradia             438462 non-null  object 
dtypes: float64(1), int64(5), object(5)
memory usage: 36.8+ MB


In [62]:
query_novo_cliente = """
INSERT INTO clientes ('ID_Cliente', 'Idade', 'Grau_escolaridade', 'Estado_civil',
       'Tamanho_familia', 'Categoria_de_renda', 'Ocupacao', 'Anos_empregado',
       'Rendimento_anual', 'Tem_carro', 'Moradia')

VALUES (6850985, 33, 'Doutorado', 'Solteiro', 1, 'Empregado', 'TI', 2, 290000, 0, 'Casa/apartamento próprio')
"""

In [63]:
# Adicionando na base de dados
with engine.connect() as conn:
    conn.execute(text(query_novo_cliente))
    conn.commit()

In [64]:
pd.read_sql_table('clientes', engine).query('ID_Cliente==6850985')

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
438461     6850985     33         Doutorado     Solteiro                1   

       Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  \
438461          Empregado       TI               2          290000.0   

        Tem_carro                   Moradia  
438461          0  Casa/apartamento próprio

In [65]:
# Verificar se foi colocado por último.
df_clientes_temp.tail(5)

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
438457     6840104     62      Ensino médio   Divorciado                1   
438458     6840222     43      Ensino médio     Solteiro                1   
438459     6841878     22   Ensino superior     Solteiro                1   
438460     6842765     59      Ensino médio       Casado                2   
438461     6842885     51      Ensino médio       Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio

In [66]:
df_clientes_atualizado = pd.read_sql_table('clientes', engine)

In [75]:
df_clientes_atualizado

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino Superior       Solteiro                1   
3          5008810     52      Ensino médio       Solteiro                1   
4          5008811     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840222     43      Ensino médio       Solteiro                1   
438458     6841878     22   Ensino superior       Solteiro                1   
438459     6842765     59      Ensino médio         Casado                2   
438460     6842885     51      Ensino médio         Casado                2   
438461     6850985     33         Doutorado       Solteiro                1   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457            Empregado  Construção Civil               8   
438458  Associado comercial            Vendas               1   
438459          Pensionista             Outro               0   
438460            Empregado            Vendas               3   
438461            Empregado                TI               2   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          103500.0          0  Casa/apartamento próprio  
438458           54000.0          0          Mora com os pais  
438459           72000.0          0  Casa/apartamento próprio  
438460          121500.0          0  Casa/apartamento próprio  
438461          290000.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]